# Add this file to your .github/workflows directory
name: Analyze with CodeGuru Reviewer
on: [push, pull_request]
permissions:
    id-token: write
    contents: write
    security-events: write 

jobs:
  build:
    name: Clone your repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

# Add your build instructions here

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: {ROLE}
        aws-region: {REGION}

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: false
      with:          
        s3_bucket: {BUCKET}
        # build_path: ./build/libs # Set a build directory if you want security findings for Java.

    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json